"""first initial migration

Revision ID: 18ca6360bf53
Revises: 
Create Date: 2024-05-22 07:03:31.330071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ca6360bf53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('school_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contacts', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('school_id')
    )
    op.create_table('fee_structure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.Column('tuition_fee', sa.Float(), nullable=False),
    sa.Column('ass_books', sa.Float(), nullable=False),
    sa.Column('diary_fee', sa.Float(), nullable=False),
    sa.Column('activity_fee', sa.Float(), nullable=False),
    sa.Column('others', sa.Float(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.school_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('guardian_name', sa.String(length=100), nullable=False),
    sa.Column('contact_number1', sa.String(length=20), nullable=False),
    sa.Column('contact_number2', sa.String(length=20), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.school_id'], ),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.school_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('additional_fee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fee_structure_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.school_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('fee_payment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.school_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fee_payment')
    op.drop_table('audit')
    op.drop_table('additional_fee')
    op.drop_table('user')
    op.drop_table('student')
    op.drop_table('fee_structure')
    op.drop_table('school')
    # ### end Alembic commands ###
