"""switched dob from string to date

Revision ID: 80ce0f8a6502
Revises: 388c7902b418
Create Date: 2024-08-06 06:06:38.993495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ce0f8a6502'
down_revision = '388c7902b418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'dob',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'dob',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
