"""add length connstraint to student id in fee payment

Revision ID: 81130f21b705
Revises: 9aadf53d025e
Create Date: 2024-08-25 07:54:43.049469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81130f21b705'
down_revision = '9aadf53d025e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_additional_fee',
    sa.Column('student_id', sa.String(length=10), nullable=False),
    sa.Column('additional_fee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['additional_fee_id'], ['additional_fee.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'additional_fee_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_additional_fee')
    # ### end Alembic commands ###
