"""students table

Revision ID: 82ef38a30262
Revises: e003420627b3
Create Date: 2024-05-10 08:28:53.994988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ef38a30262'
down_revision = 'e003420627b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.String(length=7), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('guardian_name', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
