"""initial migration

Revision ID: 849ecfdd6528
Revises: 80ce0f8a6502
Create Date: 2024-08-20 15:37:20.480619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849ecfdd6528'
down_revision = '80ce0f8a6502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'dob',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'dob',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
