"""add length connstraint to student id in fee payment

Revision ID: 9aadf53d025e
Revises: 0bf4c3743952
Create Date: 2024-08-25 07:50:54.368289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aadf53d025e'
down_revision = '0bf4c3743952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_payment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=10), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.school_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id')
    )
    op.create_table('student_additional_fee',
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('additional_fee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['additional_fee_id'], ['additional_fee.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'additional_fee_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_additional_fee')
    op.drop_table('fee_payment')
    # ### end Alembic commands ###
