"""resolved relationships

Revision ID: a8fa49e97582
Revises: 
Create Date: 2024-06-09 08:54:34.198096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8fa49e97582'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('school_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contacts', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('school_id')
    )
    op.create_table('term',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'year', name='unique_term_name_year')
    )
    op.create_table('fee_structure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.Column('tuition_fee', sa.Float(), nullable=False),
    sa.Column('ass_books', sa.Float(), nullable=False),
    sa.Column('diary_fee', sa.Float(), nullable=False),
    sa.Column('activity_fee', sa.Float(), nullable=False),
    sa.Column('others', sa.Float(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.school_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade', 'school_id', 'term_id', name='unique_grade_school_term')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.school_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.school_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('guardian_name', sa.String(length=100), nullable=False),
    sa.Column('contact_number1', sa.String(length=20), nullable=False),
    sa.Column('contact_number2', sa.String(length=20), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('left_date', sa.Date(), nullable=True),
    sa.Column('current_term_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_term_id'], ['term.id'], ),
    sa.ForeignKeyConstraint(['grade', 'school_id'], ['fee_structure.grade', 'fee_structure.school_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.school_id'], ),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('additional_fee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fee_name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.school_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fee_payment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('cf_balance', sa.Float(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.school_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fee_payment')
    op.drop_table('additional_fee')
    op.drop_table('student')
    op.drop_table('audit')
    op.drop_table('user')
    op.drop_table('fee_structure')
    op.drop_table('term')
    op.drop_table('school')
    # ### end Alembic commands ###
